[package]
name = "unroll"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.12", features = ["full"] }
quote = "0.4"
